# Generated by Django 5.1.1 on 2024-10-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_source', '0002_result_remove_education_university_contact_clinicid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.URLField(blank=True, null=True),
        ),
    ]
