# Generated by Django 5.1.1 on 2024-10-04 20:10

import storages.backends.ftp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_source', '0003_alter_question_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image_path',
            field=models.ImageField(blank=True, help_text='Изображение', null=True, storage=storages.backends.ftp.FTPStorage(location='ftp://igorjbfz_vladanak:qcZR&vy4@5.101.157.22:21/'), upload_to='media/accounts', verbose_name='Изображение'),
        ),
    ]
