# Generated by Django 5.1.1 on 2024-10-04 20:22

import dental_source.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_source', '0005_alter_account_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancedtraining',
            name='year',
            field=models.IntegerField(help_text='Год обучения', validators=[dental_source.validators.validate_year], verbose_name='Год обучения'),
        ),
    ]
