# Generated by Django 5.1.1 on 2024-10-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_source', '0006_alter_advancedtraining_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='slug',
            field=models.TextField(help_text='Ссылка на страницу на которой будет отображаться акция', verbose_name='Ссылка на страницу'),
        ),
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='slug',
            field=models.TextField(help_text='Ссылка на страницу на которой будет отображаться', verbose_name='Ссылка на страницу'),
        ),
    ]
