# Generated by Django 5.1.1 on 2024-10-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_source', '0007_alter_promotion_slug_alter_question_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='description',
        ),
        migrations.RemoveField(
            model_name='price',
            name='description',
        ),
        migrations.AddField(
            model_name='case',
            name='diagnos',
            field=models.TextField(blank=True, help_text='Диагноз', null=True, verbose_name='Диагноз'),
        ),
        migrations.AddField(
            model_name='case',
            name='introduction',
            field=models.TextField(blank=True, help_text='Первичный осмотри', null=True, verbose_name='Первичный осмотри'),
        ),
        migrations.AddField(
            model_name='case',
            name='treatment',
            field=models.TextField(blank=True, help_text='Лечение', null=True, verbose_name='Лечение'),
        ),
        migrations.AlterField(
            model_name='advancedtraining',
            name='year',
            field=models.CharField(help_text='Год обучения', max_length=25, verbose_name='Год обучения'),
        ),
        migrations.AlterField(
            model_name='education',
            name='edEnd',
            field=models.CharField(help_text='Год конца', max_length=25, verbose_name='Год конца'),
        ),
        migrations.AlterField(
            model_name='education',
            name='edStart',
            field=models.CharField(help_text='Год начала', max_length=25, verbose_name='Год начала'),
        ),
    ]
