# Generated by Django 5.1.1 on 2024-10-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_source', '0008_remove_case_description_remove_price_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='lengthInMinutes',
        ),
        migrations.AddField(
            model_name='doctor',
            name='price',
            field=models.ManyToManyField(help_text='Перечень услуг оказываемые доктором', related_name='doctor_prices', to='dental_source.price', verbose_name='Перечень услуг оказываемые доктором'),
        ),
        migrations.AddField(
            model_name='price',
            name='lengthInMinutes',
            field=models.IntegerField(default=60, help_text='Длина в минутах', verbose_name='Длина в минутах'),
        ),
    ]
