# Generated by Django 5.1.1 on 2024-10-09 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dental_source', '0009_remove_doctor_lengthinminutes_doctor_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='auth.group', verbose_name='Роль'),
        ),
    ]
