# Generated by Django 5.1.2 on 2024-10-10 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dental_source', '0011_remove_appointment_patientemail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='role',
        ),
    ]
