# Generated by Django 5.1.2 on 2024-10-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_source', '0012_remove_account_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='category',
            field=models.TextField(help_text='Категория', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='price',
            name='name',
            field=models.TextField(help_text='Название', verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='newPrice',
            field=models.TextField(help_text='Новая цена', verbose_name='Новая цена'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='oldPrice',
            field=models.TextField(help_text='Старая цена', verbose_name='Старая цена'),
        ),
    ]
